stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script: npm install && npm run build
  artifacts:
    paths:
      - dist/

deploy:
  image: tutum/curl
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
  - ./cf push
  only:
  - master